package ca.uqac.etu.weatherapikotlinclient

val WeatherIcons = mapOf(
    0 to R.drawable.clear_day,
    1 to R.drawable.partly_cloudy_day,
    2 to R.drawable.partly_cloudy_day,
    3 to R.drawable.cloudy,
    45 to R.drawable.fog,
    48 to R.drawable.fog,
    51 to R.drawable.showers_day,
    53 to R.drawable.showers_day,
    55 to R.drawable.rain,
    56 to R.drawable.rain_snow_showers_day,
    57 to R.drawable.rain_snow,
    61 to R.drawable.showers_day,
    63 to R.drawable.showers_day,
    65 to R.drawable.rain,
    66 to R.drawable.rain_snow_showers_day,
    67 to R.drawable.rain_snow,
    71 to R.drawable.snow_showers_day,
    73 to R.drawable.snow_showers_day,
    75 to R.drawable.snow,
    77 to R.drawable.sleet,
    80 to R.drawable.showers_day,
    81 to R.drawable.showers_day,
    82 to R.drawable.rain,
    85 to R.drawable.snow_showers_day,
    86 to R.drawable.snow,
    95 to R.drawable.thunder_showers_day,
    96 to R.drawable.thunder_rain,
    99 to R.drawable.thunder_rain,
)